// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0s_4-PpjzEqL0gWiFbJmlLcJqwLGxxTU',
    appId: '1:320981235042:web:376e99dffa87dac4b0283b',
    messagingSenderId: '320981235042',
    projectId: 'lawlegend-231f9',
    authDomain: 'lawlegend-231f9.firebaseapp.com',
    storageBucket: 'lawlegend-231f9.appspot.com',
    measurementId: 'G-33EQHH6GLY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAg-omAxQkzDTcndkYQkNrB0X2ha6Ct9c',
    appId: '1:320981235042:android:6ba6fee22e1a92d6b0283b',
    messagingSenderId: '320981235042',
    projectId: 'lawlegend-231f9',
    storageBucket: 'lawlegend-231f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQSMJDbiCh8OJ1K-HcILw8JfxiADcXkQ',
    appId: '1:320981235042:ios:9df6a3168efdaab4b0283b',
    messagingSenderId: '320981235042',
    projectId: 'lawlegend-231f9',
    storageBucket: 'lawlegend-231f9.appspot.com',
    iosBundleId: 'com.example.lawLegend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQSMJDbiCh8OJ1K-HcILw8JfxiADcXkQ',
    appId: '1:320981235042:ios:28caf353b31a23deb0283b',
    messagingSenderId: '320981235042',
    projectId: 'lawlegend-231f9',
    storageBucket: 'lawlegend-231f9.appspot.com',
    iosBundleId: 'com.example.lawLegend.RunnerTests',
  );
}
